"""정책 상담 에이전트가 사용하는 소스/도메인/필드 라벨과 의도 키워드 상수."""
from __future__ import annotations


SOURCE_KEY_COLUMNS = {
    "policies_processed": "policy_id",
    "hrd_trainings": "id",
    "kstartup_notices": "pbanc_sn",
    "smallloan_youth": "id",
    "myhome_notices": "id",
    "rental_houses": "id",
    # 복지서비스: 전국(welfare_central)·충북 지자체(lgcv) 모두 service_id가 키다.
    "welfare_central": "service_id",
    "lgcv": "service_id",
}

# source_table → 원본 행이 실제로 들어있는 테이블명. 대부분 source_table과 같지만,
# lgcv는 search_documents에 source_table="lgcv"로 통합되어도 원본은 충북 원천
# 테이블 welfare_chungbuk_local에 있다. 명시되지 않은 source_table은 자기 자신을 쓴다.
SOURCE_ORIGINAL_TABLES = {
    "lgcv": "welfare_chungbuk_local",
}

SOURCE_LABELS = {
    "policies_processed": "온통청년 정책",
    "hrd_trainings": "HRD-Net 훈련과정",
    "kstartup_notices": "K-Startup 창업지원공고",
    "smallloan_youth": "청년 금융상품",
    "myhome_notices": "마이홈 임대공고",
    "rental_houses": "청년 임대주택 단지",
    "welfare_central": "전국 복지서비스",
    "lgcv": "충북 지자체 복지서비스",
}

DOMAIN_LABELS = {
    "policy": "일반 정책",
    "policy_housing": "주거 정책",
    "policy_finance": "금융/복지 정책",
    "policy_training": "교육/훈련 정책",
    "policy_job": "취업 정책",
    "policy_startup": "창업 정책",
    "housing_notice": "임대 공고",
    "rental_house": "임대주택 단지",
    "loan": "청년 금융상품",
    "training": "직업훈련",
    "startup": "창업 공고",
    "welfare": "복지서비스",
}

FIELD_LABELS = {
    # Common policy table
    "policy_name": "정책명",
    "description": "개요",
    "support_content": "지원 내용",
    "apply_period": "신청 기간",
    "apply_period_type": "신청 기간 유형",
    "apply_method": "신청 방법",
    "selection_method": "선정 방법",
    "application_url": "신청 URL",
    "submit_docs": "제출 서류",
    "apply_condition": "신청 자격",
    "excluded_target": "제외 대상",
    "institution": "주관 기관",
    "oper_inst": "운영 기관",
    "income_type": "소득 조건",
    "income_etc": "소득 기타 조건",
    "min_age": "최소 연령",
    "max_age": "최대 연령",
    "job_cd": "취업 상태 조건",
    "school_cd": "학력/상태 조건",
    "region_name": "지역",
    "ref_url1": "참고 링크",
    "ref_url2": "참고 링크 2",
    # Training
    "title": "과정명",
    "sub_title": "훈련기관",
    "address": "주소",
    "tel_no": "전화번호",
    "course_man": "훈련비",
    "real_man": "실제 훈련비",
    "train_target": "훈련 대상",
    "tra_start_date": "훈련 시작일",
    "tra_end_date": "훈련 종료일",
    "title_link": "상세 링크",
    "yard_man": "정원",
    "satisfaction_score": "만족도",
    # Startup
    "notice_name": "공고명",
    "category": "분야",
    "organization": "기관",
    "target": "대상",
    "target_detail": "상세 대상",
    "business_age": "업력",
    "target_age": "연령",
    "apply_start_date": "신청 시작일",
    "apply_end_date": "신청 종료일",
    "apply_url": "신청 URL",
    "detail_url": "상세 URL",
    "contact": "문의처",
    # Loan
    "finPrdNm": "상품명",
    "lnLmt": "대출 한도",
    "irt": "금리",
    "irtCtg": "금리 유형",
    "maxTotLnTrm": "최대 대출 기간",
    "rdptMthd": "상환 방법",
    "usge": "용도",
    "trgt": "대상",
    "ofrInstNm": "제공 기관",
    "suprTgtDtlCond": "상세 조건",
    "age": "연령",
    "incm": "소득",
    "crdtSc": "신용 조건",
    "grnInst": "보증 기관",
    "jnMthd": "가입 방법",
    "rfrcCnpl": "참고 문의처",
    "cnpl": "문의처",
    "rltSite": "관련 사이트",
    "mgmDln": "마감",
    # Housing
    "supply_inst": "공급 기관",
    "house_type": "주택 유형",
    "supply_type": "공급 유형",
    "status": "공고 상태",
    "house_name": "주택명",
    "supply_units": "공급 세대",
    "deposit": "보증금",
    "monthly_rent": "월 임대료",
    "begin_date": "신청 시작일",
    "end_date": "신청 종료일",
    "post_date": "공고일",
    "myhome_url": "마이홈 URL",
    "youth_keyword": "청년 키워드",
    # Rental house
    "insttNm": "기관",
    "brtcNm": "시도",
    "signguNm": "시군구",
    "hsmpNm": "단지명",
    "rnAdres": "도로명 주소",
    "hshldCo": "세대 수",
    "suplyTyNm": "공급 유형",
    "styleNm": "주택형",
    "suplyPrvuseAr": "전용면적",
    "suplyCmnuseAr": "공용면적",
    "houseTyNm": "주택 유형",
    "heatMthdDetailNm": "난방 방식",
    "buldStleNm": "건물 형태",
    "elvtrInstlAtNm": "승강기",
    "parkngCo": "주차 대수",
    "bassRentGtn": "기본 보증금",
    "bassMtRntchrg": "기본 월 임대료",
    "bassCnvrsGtnLmt": "전환 보증금 한도",
}

INTENT_KEYWORDS = {
    "docs": ["서류", "준비", "준비물", "제출", "필요한", "필요"],
    "eligibility": ["자격", "조건", "대상", "가능", "받을 수", "해당", "지원대상"],
    "apply": ["신청", "방법", "절차", "어디", "링크", "접수", "가입"],
    "period": ["기간", "마감", "언제", "날짜", "시작", "종료"],
    "benefit": ["혜택", "지원", "내용", "금액", "총액", "얼마", "한도", "금리", "월세", "보증금"],
    "contact": ["문의", "연락", "전화", "기관", "담당"],
}
